version: "3.8"

services:

  configserver:
    image: aswinark98/configserver:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8084:8084"
    networks:
     - arknetwork
     
  eurekaserver:
    image: aswinark98/eurekaserver:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8085:8085"
    networks:
      - arknetwork
    depends_on:
      - congifserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8084/
      
  accounts:
    image: aswinark98/accountssvc:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8081:8081"
    networks:
      - arknetwork
    depends_on:
      - congifserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8084/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8085/eureka/
      
  loans:
    image: aswinark98/loansvc:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8082:8082"
    networks:
      - arknetwork
    depends_on:
      - congifserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8084/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8085/eureka/
      
  cards:
    image: aswinark98/cardssvc:0.0.1-SNAPSHOT
    mem_limit: 700m
    ports:
      - "8083:8083"
    networks:
      - arknetwork
    depends_on:
      - congifserver
      - eurekaserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8084/
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eurekaserver:8085/eureka/
 
networks:
  arknetwork: